### ISSUE TITLE
Product change for Sensotrend brand

### ISSUE THREAD

**Issue by HannuHyttinen** [Sensotrend/sensotrend-uploader#23]
### Description
The product is originally made be Tidebool. Some changes needed for Sensotrend brand.

### Requirement analysis
Known requirements (functional, performance, usability, safety):  No, this issue includes brand related changes only
Identified potential risks to the patient: None

Implementation plan:
Target schedule:
Dependencies on other issues:

### OWASP top 10
[https://github.com/OWASP/www-project-top-ten/blob/master/index.md](url)
- [ ] 1 Injection - [comments]
- [ ] 2 Broken Authentication - [comments]
- [ ] 3 Sensitive Data Exposure - [comments]
- [ ] 4 XML External Entities (XXE) - [comments]
- [ ] 5 Broken Access Control - [comments]
- [ ] 6 Security Misconfiguration - [comments]
- [ ] 7 Cross-Site Scripting XSS - [comments]
- [ ] 8 Insecure Deserialization - [comments]
- [ ] 9 Using Components with Known Vulnerabilities - [comments]
- [ ] 10 Insufficient Logging & Monitoring - [comments]

### Verification
Verification plan:
Verification date:
Verification results:

**Comment by kirsik** [comment]
This seems to be a duplicate for #37 which describes the changes in more detail, so this can be closed.
