### ISSUE TITLE
Too wide view when date/time does not match.

### ISSUE THREAD

**Issue by HannuHyttinen** [Sensotrend/sensotrend-uploader#31]
View in the image is visible when date/time does not match.
Uploader ver.: 2.33.0-alpha
Used device: Abbott FreeStyle Precision Neo.
Test setup: Win10

![image](https://user-images.githubusercontent.com/32511341/97963365-a76f9980-1dbf-11eb-8c01-65ef54297151.png)

**Comment by jlaunonen** [comment]
Should be fixed in 2.34.3.

**Comment by mrinnetmaki** [comment]
Fixed by https://github.com/Sensotrend/sensotrend-uploader/commit/224a76bf0a55dbe0d3a2b3bb3a31aa4ab479812a.
