### ISSUE TITLE
Uploader and cable for CareSens meters

### ISSUE THREAD

**Issue by HannuHyttinen** [Sensotrend/sensotrend-uploader#32]
CareSens USB cable "may not be suitable for third party software." (https://www.pharmacodiabetes.co.nz/caresens-usb-cable-hid/)

Meillä olevalla USB kaapelilla Uploader ei tosiaan toimi.
Pitäisi selvittää, millä USB kaapelilla Uploader toimii ja mitä kaapeleita Tre kaupungin diabetesvastaanotto käyttää.

**Comment by mrinnetmaki** [comment]
@kirsik testasi ja totesi toimivaksi sillä kaapelilla, jonka Diabetesvastaanotolta saa. Myös Diabetesvastaanotto on tietoinen tästä.
