### ISSUE TITLE
Localization: Finnish

### ISSUE THREAD

**Issue by HannuHyttinen** [Sensotrend/sensotrend-uploader#35]
When creating a request, please fill in parts 1 and 2 with as much information as possible. A good description is most important for us. Fields in the part 2 can also be filled when analyzing the issue.

### 1. Description
Finnish UI

### 2. Requirements and dependencies
Known requirements for
- functional: 
- performance: 
- usability: 
- safety: 

Identified potential risks to the patient:
- Mild irritation from poor translations.
- Upload problem due wrong guidance.

Dependencies on other issues: Sensotrend/sensotrend-uploader#30 
Target schedule: Needed for Tampereen kaupungin diabetesvastaanotto

### 3. Implementation details
Implementation plan: Translate locales/en/translation.json into locales/fi/translation.json .

### 3.1 OWASP top 10
[https://github.com/OWASP/www-project-top-ten/blob/master/index.md](https://github.com/OWASP/www-project-top-ten/blob/master/index.md)
- 1 Injection - No change
- 2 Broken Authentication - No change
- 3 Sensitive Data Exposure - No change
- 4 XML External Entities (XXE) - No change
- 5 Broken Access Control - No change
- 6 Security Misconfiguration - No change
- 7 Cross-Site Scripting XSS - No change
- 8 Insecure Deserialization - No change
- 9 Using Components with Known Vulnerabilities - No change
- 10 Insufficient Logging & Monitoring - No change

### 4. Verification
Verification plan:
Verification date:
Verification results:

- [x] Pass

**Comment by jlaunonen** [comment]
Localization-data has been translated. As the i18n feature is not yet complete in upstream and as some messages are hidden deep behind variables, some messages (errors maybe) might not actually be translated.

**Comment by HannuHyttinen** [comment]
Localization is good enough. Let's close this one and handle possible bugs by other issues.
