### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by jlaunonen** [Sensotrend/sensotrend-uploader#37]
### 1. Description
Instead of Sensotrend supplying Tidepool Uploader, we should white-label the application to follow Sensotrend style.

### 2. Requirements and dependencies
- [ ] Logo-images within app
- [ ] Icons
- [ ] References...
    - [ ] to Tidepool
    - [ ] to JSRF
- [ ] Server addresses

**Dependencies on other issues:** 
Required (at least) for #24, #25, #26.

### 3. Implementation details
**Implementation plan:**
- Note #35, where string replacements should be made.

**Target schedule:** 

### 3.1 OWASP top 10
[https://github.com/OWASP/www-project-top-ten/blob/master/index.md](https://github.com/OWASP/www-project-top-ten/blob/master/index.md)
- **1 Injection** - No change of functionality in client.
- **2 Broken Authentication** - No change of functionality in client.
- **3 Sensitive Data Exposure** - No change of functionality in client.
- **4 XML External Entities (XXE)** - No change of functionality in client.
- **5 Broken Access Control** - No change of functionality in client.
- **6 Security Misconfiguration** - No change of functionality in client.
- **7 Cross-Site Scripting XSS** - No change of functionality in client.
- **8 Insecure Deserialization** - No change of functionality in client.
- **9 Using Components with Known Vulnerabilities** - No change of functionality in client.
- **10 Insufficient Logging & Monitoring** - No change of functionality in client.

### 4. Verification
**Verification plan:**
To be verified by following separate tests:

1. See initial login page. It should refer to Sensotrend Uploader. Bottom right logo should not be JSRF.
2. Log in. See that next page (device list or upload preparation) does not refer to Tidepool.
3. Set environment variable `UPLOAD_URL=http://localhost:12345` (or any other port not currently in use). See initial page, that the server connection error nor developer details do not refer to Tidepool. Ensure that the error is actually not network error.

**Verification results:**
- [x] 1. Pass (2.41.0, 8.3.2022, Hannu)
- [x] 2. Pass (2.41.0, 8.3.2022, Hannu)
- [ ] 3. Pass/Fail (SW version, date)

**Comment by HannuHyttinen** [comment]
Branding is already made and launched.
