### ISSUE TITLE
Showing wrong uploader version in dialog

### ISSUE THREAD

**Issue by SamThunder** [Sensotrend/sensotrend-uploader#39]
### 1. Bug report 

**Description:** Uploader shows no updates even though there are newer version.
**Expected behavior:** Showing correct uploader versio number in dialog.
**Is the problem repeatable:**  Yes,  Start uploader and go to menu and click help and choose "check updates". Then you see dialog and uploader version number.

**Could or did it cause an incident to the patient?** No
**Screenshots:**
[If applicable, add screenshots to help explain the problem.]
![image](https://user-images.githubusercontent.com/72552410/102203369-2da7f100-3ed1-11eb-90ae-6726946bbbf2.png)

**System information:**
- **Sensotrend Uploader version:** 2.34.0
- **Device used as a data source:** 
- **Operation system and version:** Windows 10.
- **Possible other system information:**

### 2. Requirements and dependencies 
**Known requirements for**
- **functional:** 
- **performance:** 
- **usability:** 
- **safety:** 

**Dependencies on other parts of the SW:**

### 3. Implementation details
**Correction plan:**  
**Target schedule of the correction:** 

### 3.1. OWASP top 10
[https://github.com/OWASP/www-project-top-ten/blob/master/index.md](https://github.com/OWASP/www-project-top-ten/blob/master/index.md)
- [ ] **1 Injection** - [comments]
- [ ] **2 Broken Authentication** - [comments]
- [ ] **3 Sensitive Data Exposure** - [comments]
- [ ] **4 XML External Entities (XXE)** - [comments]
- [ ] **5 Broken Access Control** - [comments]
- [ ] **6 Security Misconfiguration** - [comments]
- [ ] **7 Cross-Site Scripting XSS** - [comments]
- [ ] **8 Insecure Deserialization** - [comments]
- [ ] **9 Using Components with Known Vulnerabilities** - [comments]
- [ ] **10 Insufficient Logging & Monitoring** - [comments]

### 4. Verification
To be verifified by following steps:

1. [Test step 1]
2. [Test step 2]

**Verification results:**
- [ ] 1. Pass/Fail (SW version, date)
- [ ] 2. Pass/Fail (SW version, date)

**Comment by mrinnetmaki** [comment]
Fixed by #53.
