### ISSUE TITLE
Support link does not work for me

### ISSUE THREAD

**Issue by mrinnetmaki** [Sensotrend/sensotrend-uploader#46]
### 1. Bug report 

**Description:** When clicking the support link on the main view of the app, I get redirected to a browser, but only to the page that's currently open.
**Expected behavior:** I believe this is a mailto link. I would hope it would open my email client.
**Is the problem repeatable:** Yes, 100% for me.

**Could or did it cause an incident to the patient?** No.

**System information:**
- **Sensotrend Uploader version:** v2.34.4-alpha
- **Operation system and version:** Mac OSX Big Sur
- **Possible other system information:** Tested with two users. One has Microsoft Outlook set as the email client, one has no default email client set.

### 2. Requirements and dependencies 
**Known requirements for**
- **functional:** None.
- **performance:** None.
- **usability:** None.
- **safety:** None.

**Dependencies on other parts of the SW:**

### 3. Implementation details
**Correction plan:**  
**Target schedule of the correction:** 

### 3.1. OWASP top 10
[https://github.com/OWASP/www-project-top-ten/blob/master/index.md](https://github.com/OWASP/www-project-top-ten/blob/master/index.md)
- [ ] **1 Injection** - [comments]
- [ ] **2 Broken Authentication** - [comments]
- [ ] **3 Sensitive Data Exposure** - [comments]
- [ ] **4 XML External Entities (XXE)** - [comments]
- [ ] **5 Broken Access Control** - [comments]
- [ ] **6 Security Misconfiguration** - [comments]
- [ ] **7 Cross-Site Scripting XSS** - [comments]
- [ ] **8 Insecure Deserialization** - [comments]
- [ ] **9 Using Components with Known Vulnerabilities** - [comments]
- [ ] **10 Insufficient Logging & Monitoring** - [comments]

### 4. Verification
To be verifified by following cases:

1. [Test case 1]
2. [Test case 2]

**Verification results:**
- [ ] 1. Pass/Fail (SW version, date)
- [ ] 2. Pass/Fail (SW version, date)

**Comment by kirsik** [comment]
This occurs also in Windows 10, 2.34.4-alpha

**Comment by mrinnetmaki** [comment]
Changed the support feature to open a webpage instead of opening a mail client. See #47 and #54.
