### ISSUE TITLE
Instructions for use

### ISSUE THREAD

**Issue by kirsik** [Sensotrend/sensotrend-uploader#48]
## 1. Background & description

*Why?*

Requirement source: internal + customer, see customer reguirements + regulatory, see regulatory requirements

Describe here
- The need for the feature (initiated from external/internal request)
- The goal of the feature

## 2. Requirements

*What?*

#### Customer requirements
- Device specific uploading guides required ~9/2020 by Elina Pimiä, Tampere outpatient clinic

#### Regulatory requirements
- General requirements in [MDR](https://eur-lex.europa.eu/legal-content/FI/TXT/?uri=CELEX%3A32017R0745), annex I, clause 23.1.
- Content of the label in [MDR](https://eur-lex.europa.eu/legal-content/FI/TXT/?uri=CELEX%3A32017R0745), annex I, clause 23.2.
- Content of the instruction of use in [MDR](https://eur-lex.europa.eu/legal-content/FI/TXT/?uri=CELEX%3A32017R0745), annex I, clause 23.4.
- Requirements for electronic instruction in regulation [207/2012](https://eur-lex.europa.eu/legal-content/FI/TXT/?uri=celex%3A32012R0207).
- Language requirements in Finland, [Laki terveydenhuollon laitteista ja tarvikkeista] (https://www.finlex.fi/fi/laki/alkup/2010/20100629), 12 §.
- Standard followed: ISO 1041:2008 & A1:2013 Information supplied by the manufacturer of medical devices

#### Functional requirements

Prerequisites
End results
Other functional requirements
Error situations

#### Performance requirements

Memory usage
Time of the operation
Simultaneous users

#### Usability requirements

Intended users and their skills
Instructions for use
Browser/mobile
Accessibility

#### Risk analysis

*Instructions: 1. Identify risks that may arise due to this issue. 2. Check the product's existing risks and how they may appear in this issue. 3. Describe how each risk is taken into account in this issue. If new risks or risk controls are identified, invite a risk workshop to discuss these.*

- [x] Risk analysis done and risks updated according to QMS

**Identified risks (mark potential new ones by bolding them):**
This issue is for instructions only. It includes risk control actions defined in risk list. No identified risks.

**Related risks from the risk list:**
Risks including risk control actions by user instructions.

**Control and actions (all risks from previous lists):**
None

## 3. Implementation

*How?*

Device specific uploading guides in https://github.com/Sensotrend/sensotrend-connect-ui/pull/2.
Safety information fulfilling MDR requirements in https://github.com/Sensotrend/sensotrend-connect-ui/pull/30.
Swedish safety information in https://github.com/Sensotrend/sensotrend-connect-ui/pull/31. 

i18n part1 in https://github.com/Sensotrend/sensotrend-connect-ui/pull/33.

## 4. Verification

**General description of how to test the feature**
This issue is for instructions only. To be verified by review of implementation pull requests.

**Comment by HannuHyttinen** [comment]
All pull requests linked are merged. This one seems to be ready.
