### ISSUE TITLE
Uploader for Poolprax

### ISSUE THREAD

**Issue by kirsik** [Sensotrend/sensotrend-uploader#60]
## 1. Background & description

*Why?*

Requirement source: Poolprax

The goal is to deliver a suitable version of the Sensotrend Uploader product to Poolprax AG in Switzerland.

## 2. Requirements

*What?*

#### Functional requirements

Prerequisites

End results
- Signin in by Poolprax's user information, not Sensotrend account
- Data is uploaded to Poolprax's data platform
- Localized version of Uploader (English, German, prepared for French and Italian)
- Branded for Poolprax (styles, logos)

Other functional requirements

Error situations

#### Performance requirements

Memory usage
Time of the operation
Simultaneous users

#### Usability requirements

Intended users and their skills
Instructions for use
Browser/mobile
Accessibility

#### Regulatory requirements

- Requirement coming from QMS, incl. compliance with ISO 13485 and IEC 62304. 
- In addition, manufacturer requirements coming from [Swiss MedDo art. 46-50](https://www.fedlex.admin.ch/eli/cc/2020/552/en#chap_6), incl. documentation requirements coming from [MDR annex II and III](https://drive.google.com/file/d/1BXQ5xdHgBF8V7zIQbgB73qtEYCzbb5B3/view?usp=sharing).

#### Risk analysis

*Instructions: 1. Identify risks that may arise due to this issue. 2. Check the product's existing risks and how they may appear in this issue. 3. Describe how each risk is taken into account in this issue. If new risks or risk controls are identified, invite a risk workshop to discuss these.*

- [ ] Risk analysis done and risks updated according to QMS

Identified risks (mark potential new ones by bolding them):
1. [Description]
2. [Description]

Related risks from the risk list:
1. [Identifier, description]
2. [Identifier, description]

Control and actions (all risks from previous lists):
1. [Risk, controls, actions]
2. [Risk, controls, actions]

## 3. Implementation

*How?*

Describe here
- Architectural decisions
- Which other products or product components does this feature use?
- Which external libraries etc. does this feature use?

#### Security check-up

Check that the OWASP top 10 have been taken into account.

[https://github.com/OWASP/www-project-top-ten/blob/master/index.md](https://github.com/OWASP/www-project-top-ten/blob/master/index.md)
- [ ] **1 Injection** - [comments]
- [ ] **2 Broken Authentication** - [comments]
- [ ] **3 Sensitive Data Exposure** - [comments]
- [ ] **4 XML External Entities (XXE)** - [comments]
- [ ] **5 Broken Access Control** - [comments]
- [ ] **6 Security Misconfiguration** - [comments]
- [ ] **7 Cross-Site Scripting XSS** - [comments]
- [ ] **8 Insecure Deserialization** - [comments]
- [ ] **9 Using Components with Known Vulnerabilities** - [comments]
- [ ] **10 Insufficient Logging & Monitoring** - [comments]

## 4. Verification

To be verified by the following cases:

1. Functional verification by the customer.

Verification results:

- [x] 1. Pass (email Gnägi->Rinnetmäki 16.10.2021)

**Comment by HannuHyttinen** [comment]
Implementation is made by Poolprax and verified as seen in this issue. This is ready now on our point of view.
